"""add_sync_models

Revision ID: 3c995a8a9819
Revises: d1dba255e4e7
Create Date: 2026-02-09 09:47:17.570589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c995a8a9819'
down_revision = 'd1dba255e4e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('change_data', sa.JSON(), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_changes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_changes'))
    )
    with op.batch_alter_table('sync_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_changes_synced'), ['synced'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_changes_timestamp'), ['timestamp'], unique=False)

    op.create_table('sync_conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('device1_id', sa.String(length=36), nullable=False),
    sa.Column('device2_id', sa.String(length=36), nullable=False),
    sa.Column('device1_data', sa.JSON(), nullable=False),
    sa.Column('device2_data', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_conflicts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_conflicts'))
    )
    op.create_table('sync_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_devices_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_devices')),
    sa.UniqueConstraint('device_id', name=op.f('uq_sync_devices_device_id'))
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items_synced', sa.Integer(), nullable=True),
    sa.Column('items_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sync_devices.id'], name=op.f('fk_sync_logs_device_id_sync_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_logs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_logs')
    op.drop_table('sync_devices')
    op.drop_table('sync_conflicts')
    with op.batch_alter_table('sync_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_changes_timestamp'))
        batch_op.drop_index(batch_op.f('ix_sync_changes_synced'))

    op.drop_table('sync_changes')
    # ### end Alembic commands ###