"""Initial database schema

Revision ID: 74c972832792
Revises: 
Create Date: 2026-01-19 08:30:27.338636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c972832792'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)

    op.create_table('import_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('connection_status', sa.String(length=20), nullable=True),
    sa.Column('last_connection_test', sa.DateTime(), nullable=True),
    sa.Column('connection_error', sa.Text(), nullable=True),
    sa.Column('import_options', sa.JSON(), nullable=False),
    sa.Column('auto_import', sa.Boolean(), nullable=False),
    sa.Column('import_schedule', sa.String(length=100), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('last_successful_sync', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('total_imported', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_import_configs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_configs'))
    )
    with op.batch_alter_table('import_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_configs_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_configs_user_id'), ['user_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tags_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('reading_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_knowledge_items_author_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_knowledge_items_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_items'))
    )
    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_items_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_title'), ['title'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('knowledge_item_id', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], name=op.f('fk_attachments_knowledge_item_id_knowledge_items')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_attachments_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_knowledge_item_id'), ['knowledge_item_id'], unique=False)

    op.create_table('knowledge_item_tags',
    sa.Column('knowledge_item_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], name=op.f('fk_knowledge_item_tags_knowledge_item_id_knowledge_items')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_knowledge_item_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('knowledge_item_id', 'tag_id', name=op.f('pk_knowledge_item_tags'))
    )
    op.create_table('knowledge_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_item_id', sa.String(), nullable=False),
    sa.Column('to_item_id', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_knowledge_links_created_by_users')),
    sa.ForeignKeyConstraint(['from_item_id'], ['knowledge_items.id'], name=op.f('fk_knowledge_links_from_item_id_knowledge_items')),
    sa.ForeignKeyConstraint(['to_item_id'], ['knowledge_items.id'], name=op.f('fk_knowledge_links_to_item_id_knowledge_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_links'))
    )
    with op.batch_alter_table('knowledge_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_links_from_item_id'), ['from_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_links_to_item_id'), ['to_item_id'], unique=False)

    op.create_table('knowledge_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('knowledge_item_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_knowledge_versions_created_by_users')),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], name=op.f('fk_knowledge_versions_knowledge_item_id_knowledge_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_versions'))
    )
    with op.batch_alter_table('knowledge_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_versions_knowledge_item_id'), ['knowledge_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_versions_knowledge_item_id'))

    op.drop_table('knowledge_versions')
    with op.batch_alter_table('knowledge_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_links_to_item_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_links_from_item_id'))

    op.drop_table('knowledge_links')
    op.drop_table('knowledge_item_tags')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_knowledge_item_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_items_title'))
        batch_op.drop_index(batch_op.f('ix_knowledge_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_items_category_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_items_author_id'))

    op.drop_table('knowledge_items')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_user_id'))
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('import_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_configs_user_id'))
        batch_op.drop_index(batch_op.f('ix_import_configs_platform'))

    op.drop_table('import_configs')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###